### ISSUE TITLE
Pulling holds

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#191]
## Functionality needed

- [ ] We need a way to update Status from “Open - Not Yet Filled” to “Open - Awaiting Pickup” or “Open- Awaiting delivery” or “Closed….” etc.
- [ ] The Actions drop down doesn’t seem to have a way to update status of hold on the item – only in the Patron’s account allows that – it would be good to have a “Change status” on the Actions drop down from the item request page.
- [ ] Also – need a way to send Patron notice of the outcome of their request (whether cancelled or pulled and waiting on the hold shelf).

## Steps in FOLIO

- [ ] App: Requests
- [ ] Check box that says “Pages”
- [ ] View all items that appear and pull book from the shelf
- [ ] Update status – 
- [ ] Go into Apps> Users > Search for requesting patron
- [ ] Scroll to Patron’s Requests 
- [ ] Then – go separately into Notifications to send Patron notice up the update?

**Comment by katallm** [comment]
Claire and I walked through this today as well, since we signed up in the original user stories slides and wanted to give it a try. 

Steps in FOLIO 

1. App: Requests
2. Click Actions button 
3. Select "Print pick slips for [location]"
4. Print dialog pops up, should show a pick slip with request
5. Click print

Notes
- [ ] We need a pick slip template (we made a simple one but it could use updating)
- [ ] Permissions dictate which locations you can generate a pick slip for. 
- [ ] Each hold prints on its own page which is good, in keeping with our current workflows for paging
- [ ] Can export a list of all requests in any status, including locations other than your service point by clicking "export search results to csv"
- [ ] If an item is not on the pick list and is checked in, it will prompt a pop up message with the option to print a pick slip

**Comment by jwfuller** [comment]
You need to be assigned to a specific Service Point to be able to do this, so people covering for a branch will need additional service points

**Comment by jwfuller** [comment]
Relates to #119

**Comment by jwfuller** [comment]
## ToDos

- [ ] Create a Hold without Paging (rush holds). We might be able to manage this via Circulation Rules
- [ ] Cancelling because the item is not on the shelf (required a template to be created)
- [ ] If you cancel a Hold, we need to be able to mark an item as Missing (can "Cancel & Mark as Missing" in Sierra)
- [x] Edit pickup location on a user's behalf
- [ ] Need a template for a Transit Slip

**Comment by katallm** [comment]
Created a temporary pick slip template. 

![folio-notice-template-pick-slip](https://user-images.githubusercontent.com/93286339/156465801-8067841e-c8cb-422b-a64b-23bd33505b1c.png)

**Comment by katallm** [comment]
Hold slip - temporary template: 

![folio-notice-template-hold-slip](https://user-images.githubusercontent.com/93286339/156467014-058d182e-6d12-4f8f-b52f-2ac55c57bda8.png)
