### ISSUE TITLE
Work to get list into proper Issues

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#52]
_This is for personally getting organized_

## Open

- [x] [CU Boulder Holdings/Items Map](https://docs.google.com/spreadsheets/d/1x-yT87CUJpNErJvbZ0lWREl1CghvyFOfA7jRZzyzBOw/edit#gid=1936558381)
- [x] #204 

## General Questions

- [x] ~How will FOLIO work with RAPID and IDS software to determine real-time availability (RTAC).~ #51 
- [x] ~Known Item Searching: ILLiad addons (360 Core, z39.50, Publication Finder, RAPID, [IDS](https://my.idsproject.org/login.php), DOCLINE, Occam's Reader)~ Will need to work with Rapid and IDS to update configuration
- [x] #74
- [x] Borrowing Loans with variable due dates
- [x] #71

## RA Pod

- [x] Mapping [locations](https://github.com/culibraries/folio/labels/Locations)
- [x] ~Mapping for addresses, user/patron groups [Working Doc - Circ Rules and Settings FOLIO](https://docs.google.com/document/d/17C4jep70MlKBrkEPKCM4_7HW35BBs1ba_U2mJsAlGJQ/edit#heading=h.iuygs442uqyf)~ See #17 and #55 
- [x] ~[Proposed Library Borrower Tiers and Loan Privileges 2021](https://docs.google.com/spreadsheets/d/10ouMjTPxGCAzGAlyrxQW4L6DawbLt9caB_L86fa4hDg/edit#gid=1624640580)~
- [x] Is Prospector in-scope for this pod?
- [x] Are Self-checkout machines in scope for this pod? No, tracked in #12 
- [x] Ability to add more statuses in general (ILL/Prospector distinctions, view out locations).
- [x] [User Stories for FOLIO @ CU](https://docs.google.com/presentation/d/1JsHEpKK9T3wNPiu4EwbmFGkKB5NpzcoEDghTB81bkGw/edit#slide=id.gcce6470ce0_0_14) - renew, return, inventory report (running lists?), cancelling holds. What about adding bibs/instances for brief ILLs?
- [x] Will need Inventory app to create brief bibs/instances
- [x] ~How do you place a hold on an item? [FOLIO Wiki Pages, Holds, and Recalls](https://wiki.folio.org/display/FOLIOtips/Request+Type+Whitelist+Table+-+behavior+of+Recall%2C+Hold+and+Page)~ Deal with in RA and Disc Pods
- [x] #118
- [x] ~Find user account with the option of searching by ILLiad Username (currently in the "q" index in Sierra)~ Identikey is username in both systems
- [x] Bulk delete item and bib records for ILL borrowed materials
- [x] ~Where to input special messages for circulation, such as "Check for 2 pieces," etc.?~ Circulations notes are supported
- [x] ~TN - Include in "Identifiers," Other; FOLIO needs to be able to read the barcodes on our yellow slips~ Need to make sure there is a good process for inputting these barcodes
- [x] "Save and Close" did not seem to work. The screen just sits there and does nothing.
- [x] ~TN - Include in "Identifiers," Other~ duplicate of two lines up
- [x] ~Where to input the lender?~ Consider in #126
- [x] ~Which drop down boxes need to have data that indicates it's an ILL?~ Consider in #126

## Discovery Pod

- [x] #67
- [x] #80
- [x] [EDS Custom Catalog Questionaire](https://docs.google.com/document/d/17BEPrNdXY_56mRwj8MPdEx2TSrOps-4cPhDHw5SeVyw/edit)
- [x] [Open EBSCO EDS Questions](https://docs.google.com/document/d/12U3Bg6CJSAhvd2JIh0-jtYM8Hcmf2-dJcRHrrtS9bSU/edit#heading=h.snywpiiaqu57)
- [x] [Chinook Exports](https://docs.google.com/presentation/d/1dVw4jP-0tGJKAROLoVshWnkFlEkvML8d5So2H2GKnh8/edit#slide=id.gf327c6f2fe_0_0)

## INN-Reach Integration/Prospector

- [x] Holdings and Items may have permanent and/or temporary location values. Locations are set at the holdings level and inherited by the item record, but can be overridden at the item record. From [FOLIO Wiki](https://wiki.folio.org/display/FOLIOtips/Settings+-+Tenant+-+Location+Setup)
- [x] Sharing a FOLIO instance with Law but having separate ILL and patron accounts (Sierra).
  * One FOLIO, divided at the library location, and one discovery layer, and one ezproxy
  * Will need to look at circ rules, patron groups
- [x] [Loan Policies in INN-Reach](https://github.com/folio-org/mod-circulation/blob/master/doc/circulationrules.md)
- [x] #128
- [x] - How will [EDS/Alma work with Prospector](http://www.ncip.info/inn-reach-dcb.html)? 
- [x] Springer and Swank in Prospector - discuss

**Comment by libraryfemme** [comment]
Springer and Swank in Prospector - discuss
